---

- name: Run the test playbook
  become: True
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Get the username running this playbook
      become: false
      local_action: command whoami
      register: username_on_the_host

    - name: Display the User name
      ansible.builtin.debug:
        msg: "Hello User {{ username_on_the_host.stdout }} from Jenkins and Ansible!!"
    - name: Deploy static website
      copy:
        src: index.html
        dest: /docker-ansible-jenkins/
