---
- hosts: localhost
  gather_facts: false
  become: True
  tasks:
    - name: Start the container
      docker_container:
        name: chandrikaapp
        image: "c506521615/chandrikaapp"
        state: started
        published_ports:
          - 0.0.0.0:8090:8090
